# Site Settings
title: Soonwoo Choi
email: tnsdn94560@gmail.com
baseurl: ""
url: ""
github_username: swchoigit

# Build settings
plugins:
  - jekyll-feed

# Markdown Processing
kramdown:
  hard_wrap: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations: ["import"]

# Outputting
permalink: /:categories/:year-:month-:day-:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
