# Site Settings
title: Soonwoo Choi
url: "https://soonwoochoi.github.io"
domain: "soonwoochoi.github.io"
github_username: swchoigit

# Build settings
plugins:
  - jekyll-feed

# Conversion
highlighter: none

# Markdown Processing
kramdown:
  syntax_highlighter: null
  syntax_highlighter_opts:
    disable: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations: ["import"]

# Outputting
permalink: /:categories/:year-:month-:day-:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
