# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

# Site settings
title: Soonwoo Choi
email:
description:
baseurl: ""
url: "https://swchoigit.github.io"
twitter_username:
github_username: swchoigit

permalink: /posts/:categories/:year-:month-:day-:title/
paginate: 5
paginate_path: "/page:num/"

category_archive:
  type: liquid
  path: /categories/

defaults:
  - scope:
      type: "posts"
    values:
      layout: "single"
      toc: true
      toc_sticky: true
      toc_label: "On this page"
      class: wide

include:
  - _pages
